### ISSUE TITLE
problem when pull the new code 

### ISSUE THREAD

**Issue by naturalbeau** [jhuapl-boss/django-oidc#4]
I have followed the simple django-keycloak integration example(http://blog.jonharrington.org/static/integrate-django-with-keycloak/) to setup keycloak for authorization. It was working as expect few days ago. But yesterday I created the same project in a clean VM and installed the django-oidc, drf-oidc-auth , boss-oidc libraries using the same link as before, I get the following error when I try to do "python3 manage.py migrations" or "python3 manage.py runserver". Can anyone point out which direction I should go?

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f806019c510>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/keycloak/keycloakexample/keycloakexample/urls.py", line 29, in <module>
    url(r'openid/', include('djangooidc.urls')),
  File "/usr/local/lib/python3.5/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/views.py", line 21, in <module>
    CLIENTS = OIDCClients(settings)
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/oidc.py", line 148, in __init__
    self.client[key] = self.create_client(**val)
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/oidc.py", line 177, in create_client
    behaviour=kwargs["behaviour"], verify_ssl=verify_ssl, **args)
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/oidc.py", line 31, in __init__
    client_authn_method, keyjar, verify_ssl)
  File "/usr/local/lib/python3.5/dist-packages/oic/oic/__init__.py", line 335, in __init__
    config=config, client_cert=client_cert)
  File "/usr/local/lib/python3.5/dist-packages/oic/oauth2/__init__.py", line 212, in __init__
    self.issuer = self.config['issuer']
TypeError: 'bool' object is not subscriptable

**Comment by ctornatta** [comment]
@naturalbeau I ran across this as well and solved it (at least temporarily) by pinning oic: `oic==0.12.0` in my `requirements.txt`.

**Comment by naturalbeau** [comment]
@ctornatta Thanks. That works.

**Comment by derek-pryor** [comment]
Created #5  that fixes this issue
