### ISSUE TITLE
oic==0.14.0 breaks on quote_from_bytes()

### ISSUE THREAD

**Issue by k-dahl** [jhuapl-boss/django-oidc#7]
oic==0.14.0 seems to have broken django-oidc again in different way - now getting:

```
[24/May/2018 17:50:05] "GET /openid/openid/KeyCloak?next=/secure/ HTTP/1.1" 302 0
quote_from_bytes() expected bytes
Internal Server Error: /openid/callback/login/
Traceback (most recent call last):
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/djangooidc/views.py", line 87, in authz_cb
    userinfo = client.callback(query, request.session)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/djangooidc/oidc.py", line 108, in callback
    authn_method=self.registration_response["token_endpoint_auth_method"])
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/oic/oic/__init__.py", line 681, in do_access_token_request
    authn_method, **kwargs)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/oic/oauth2/__init__.py", line 740, in do_access_token_request
    **kwargs)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/oic/oauth2/__init__.py", line 475, in request_info
    **kwargs)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/oic/oauth2/__init__.py", line 605, in init_authentication_method
    cis, request_args, http_args, **kwargs)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/oic/utils/authn/client.py", line 113, in construct
    credentials = "{}:{}".format(quote_plus(user), quote_plus(passwd))
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/future/backports/urllib/parse.py", line 716, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/future/backports/urllib/parse.py", line 700, in quote
    return quote_from_bytes(string, safe)
  File "/home/kevin/Source/keycloak_login/venv/lib64/python3.6/site-packages/future/backports/urllib/parse.py", line 725, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```
pinning back to 0.13.0 solves the error.

**Comment by derek-pryor** [comment]
Thanks for the notification. We pinned the version of `oic` back to `0.13.0` after you opened the issue but failed to update and close the issue.
